### ISSUE TITLE
Repo doesn't match README

### ISSUE THREAD

**Issue by ColumPaget** [phillbush/ctrlmenu#1]
Hi,

I've been playing around with ctrlmenu, and I've found that the -e and -x commands described in the README don't seem to be supported. Looking into main.c they don't seem to be among the parsed options. Also png icons are not supported, as implied in the readme, only xpm are supported. All this leads me to think that the source code here might be older than the accompanying readme?

regards,

Colum

**Comment by sewnie** [comment]
hello @phillbush it has been months since this issue and not 1 comment

**Comment by phillbush** [comment]
Oh, sorry about that.
I had some time idle from github and forgot about this issue.

Ctrlmenu is an experimental project of mine, so there will be lots of breaking changes as I feel the need to try something.
I may end up merging a few things I experimented in ctrlmenu into xmenu.
